name: front_end
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}

          script: |
           export PATH="$HOME/.fnm:$PATH"
           [ -s "$HOME/.fnm/fnm.sh" ] && \. "$HOME/.fnm/fnm.sh"
           fnm install 14
           fnm use 14
           cd Full-Stack-Deployment/frontend
           git pull origin main
           npm install
           npm run dev
