name: front_end
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}

          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  
            nvm use 18
            echo "Current PATH: $PATH"
            echo "Node version: $(node -v)"
            echo "NPM version: $(npm -v)"
           
            cd Full-Stack-Deployment/frontend
            git pull origin main
            npm install
            pm2 restart npm --name "frontend-app" -- run dev -- --host 0.0.0.0
