name: docker_image
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: build docker image
        run: docker build -t frontend:latest ./frontend
      - name: install Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'frontend:latest'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      
    
    
